In [ ]:
import sys
import pandas as pd
from pathlib import Path

sys.path.append(str(Path("..").resolve()))
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)

from etl.extract import load_datasets
from etl.transform import optimize_dataframe, transform_customers, transform_inventory, transform_orders, transform_products, transform_promotions, transform_reviews
from etl.load import save_dataframe_as_csv, save_dataframe_as_parquet

#CARGA DE DATASETS y optimización
datasets = load_datasets(Path("../data")) 

for file_name, df in datasets.items():
    datasets[file_name] = optimize_dataframe(df, name = file_name)

#Solo intenta usar el tipo de dato mas chico posible sin romper los datos. Optimización de memoria entre 50%-80%

--- Inicio de Optimización en archivo: ecommerce_brands ---
📊 Tamaño previo: 0.00 MB | Filas: 15
✅ Ejecución exitosa.
📊 Tamaño optimizado: 0.00 MB
📉 Reducción de memoria: 20.78%
--- Inicio de Optimización en archivo: ecommerce_categories ---
📊 Tamaño previo: 0.00 MB | Filas: 10
✅ Ejecución exitosa.
📊 Tamaño optimizado: 0.00 MB
📉 Reducción de memoria: 6.57%
--- Inicio de Optimización en archivo: ecommerce_customers ---
📊 Tamaño previo: 0.21 MB | Filas: 334
✅ Ejecución exitosa.
📊 Tamaño optimizado: 0.12 MB
📉 Reducción de memoria: 42.61%
--- Inicio de Optimización en archivo: ecommerce_inventory ---
📊 Tamaño previo: 0.02 MB | Filas: 187
✅ Ejecución exitosa.
📊 Tamaño optimizado: 0.01 MB
📉 Reducción de memoria: 36.21%
--- Inicio de Optimización en archivo: ecommerce_orders ---
📊 Tamaño previo: 0.39 MB | Filas: 1000
✅ Ejecución exitosa.
📊 Tamaño optimizado: 0.15 MB
📉 Reducción de memoria: 61.95%
--- Inicio de Optimización en archivo: ecommerce_order_items ---
📊 Tamaño previo: 0.13 MB | Filas: 2933
✅ Ejecución exitosa.
📊 Tamaño optimizado: 0.04 MB
📉 Reducción de memoria: 70.77%
--- Inicio de Optimización en archivo: ecommerce_products ---
📊 Tamaño previo: 0.04 MB | Filas: 100
✅ Ejecución exitosa.
📊 Tamaño optimizado: 0.04 MB
📉 Reducción de memoria: -0.25%
--- Inicio de Optimización en archivo: ecommerce_promotions ---
📊 Tamaño previo: 0.00 MB | Filas: 10
✅ Ejecución exitosa.
📊 Tamaño optimizado: 0.00 MB
📉 Reducción de memoria: 14.74%
--- Inicio de Optimización en archivo: ecommerce_reviews ---
📊 Tamaño previo: 0.05 MB | Filas: 200
✅ Ejecución exitosa.
📊 Tamaño optimizado: 0.01 MB
📉 Reducción de memoria: 70.37%
--- Inicio de Optimización en archivo: ecommerce_suppliers ---
📊 Tamaño previo: 0.00 MB | Filas: 8
✅ Ejecución exitosa.
📊 Tamaño optimizado: 0.00 MB
📉 Reducción de memoria: -2.87%
--- Inicio de Optimización en archivo: ecommerce_warehouses ---
📊 Tamaño previo: 0.00 MB | Filas: 5
✅ Ejecución exitosa.
📊 Tamaño optimizado: 0.00 MB
📉 Reducción de memoria: -3.45%

In [322]:
for name, df in datasets.items():
    null_cols = df.isnull().sum()
    null_cols = null_cols[null_cols > 0]

    if not null_cols.empty:
        print(f"\n📂 {name}")
        print(null_cols.to_frame("nulos").assign(porcentaje=lambda x: (x["nulos"] / len(df) * 100).round(2)))

📂 ecommerce_categories
                    nulos  porcentaje
parent_category_id      7        70.0

📂 ecommerce_orders
              nulos  porcentaje
promotion_id    724        72.4
notes           837        83.7

In [323]:
#Verificamos que el ecommerce_categories tiene 7 filas con valores nulos en parent_category_id.

df_categories = datasets['ecommerce_categories']

# Ver exactamente cuáles son las filas con nulos en esa columna
df_categories[df_categories["parent_category_id"].isnull()]

,category_id,category_name,description,parent_category_id,is_active,display_order
0,1,Electrónica,Productos de electrónica,NaN,True,1
1,2,Ropa,Productos de ropa,NaN,True,2
2,3,Hogar,Productos de hogar,NaN,True,3
3,4,Deportes,Productos de deportes,NaN,True,4
6,7,Belleza,Productos de belleza,NaN,True,7
7,8,Alimentos,Productos de alimentos,NaN,False,8
8,9,Jardín,Productos de jardín,NaN,True,9

Estos valores no los modifico por que considero que son categorias que no tienen una raíz padre, lo cual puede ser correcto.

In [324]:
# Vamos a verificar el dataset ecommerce_orders que tiene varias filas con nulos

df_orders = datasets['ecommerce_orders']
df_orders[df_orders["promotion_id"].isnull()]
df_orders[df_orders["notes"].isnull()]
#No modificamos las ordenes con promotion_id null por que tal vez son ordenes que no tenían promoción o un precio de descuento al momento de hacer la compra.
#Tampoco modificamos campo notes.

,order_id,order_number,customer_id,order_date,status,subtotal,discount_percent,shipping_cost,tax_amount,total_amount,payment_method,shipping_method,promotion_id,notes
1,2,ORD-20230315-00002,21,2023-03-15,procesando,1379.520020,6,360,289.700012,1946.449951,paypal,same_day,10.0,NaN
2,3,ORD-20250807-00003,313,2025-08-07,enviado,1652.000000,16,30,346.920013,1764.599976,debit_card,express,NaN,NaN
3,4,ORD-20250811-00004,195,2025-08-11,procesando,1489.880005,2,300,312.869995,2072.949951,paypal,pickup,7.0,NaN
4,5,ORD-20251012-00005,257,2025-10-12,enviado,989.119995,6,470,207.720001,1607.489990,bank_transfer,same_day,NaN,NaN
5,6,ORD-20230126-00006,127,2023-01-26,cancelado,4588.899902,17,480,963.669983,5252.459961,paypal,pickup,NaN,NaN
6,7,ORD-20250716-00007,189,2025-07-16,cancelado,4813.660156,13,470,1010.869995,5668.750000,credit_card,same_day,NaN,NaN
8,9,ORD-20230122-00009,255,2023-01-22,entregado,784.710022,18,240,164.789993,1048.250000,debit_card,same_day,2.0,NaN
9,10,ORD-20240116-00010,56,2024-01-16,pendiente,2307.270020,4,230,484.529999,2929.510010,cash_on_delivery,express,NaN,NaN
10,11,ORD-20240818-00011,103,2024-08-18,enviado,3727.189941,3,420,782.710022,4818.080078,credit_card,same_day,NaN,NaN
11,12,ORD-20231003-00012,268,2023-10-03,procesando,3450.879883,2,10,724.679993,4116.540039,bank_transfer,standard,NaN,NaN
12,13,ORD-20230705-00013,180,2023-07-05,pendiente,3413.929932,20,280,716.929993,3728.070068,credit_card,standard,NaN,NaN
14,15,ORD-20250505-00015,301,2025-05-05,enviado,3595.729980,18,220,755.099976,3923.600098,debit_card,pickup,NaN,NaN
15,16,ORD-20240705-00016,17,2024-07-05,cancelado,1678.750000,4,390,352.540009,2354.139893,paypal,standard,NaN,NaN
17,18,ORD-20250928-00018,256,2025-09-28,cancelado,2398.719971,1,280,503.730011,3158.459961,bank_transfer,express,NaN,NaN
18,19,ORD-20241208-00019,253,2024-12-08,entregado,3739.909912,18,340,785.380005,4192.109863,paypal,express,NaN,NaN
20,21,ORD-20231106-00021,275,2023-11-06,entregado,3012.389893,1,40,632.599976,3654.870117,bank_transfer,same_day,NaN,NaN
21,22,ORD-20250119-00022,15,2025-01-19,procesando,3476.429932,13,240,730.049988,3994.540039,bank_transfer,same_day,NaN,NaN
23,24,ORD-20240604-00024,93,2024-06-04,pendiente,2706.580078,18,0,568.380005,2787.780029,paypal,standard,NaN,NaN
24,25,ORD-20231012-00025,198,2023-10-12,entregado,667.950012,8,40,140.270004,794.780029,paypal,standard,10.0,NaN
25,26,ORD-20251028-00026,183,2025-10-28,procesando,1637.939941,6,470,343.970001,2353.629883,debit_card,standard,NaN,NaN
26,27,ORD-20251008-00027,147,2025-10-08,enviado,1713.699951,16,100,359.880005,1899.390015,debit_card,same_day,NaN,NaN
27,28,ORD-20241208-00028,220,2024-12-08,enviado,301.309998,17,100,63.279999,413.369995,debit_card,same_day,NaN,NaN
28,29,ORD-20230204-00029,134,2023-02-04,entregado,112.790001,0,280,23.690001,416.480011,credit_card,same_day,NaN,NaN
29,30,ORD-20230518-00030,70,2023-05-18,entregado,1065.839966,0,140,223.830002,1429.670044,paypal,pickup,9.0,NaN
31,32,ORD-20250804-00032,124,2025-08-04,pendiente,1343.359985,17,170,282.109985,1567.099976,debit_card,pickup,NaN,NaN
32,33,ORD-20231118-00033,6,2023-11-18,entregado,1198.099976,7,310,251.600006,1675.829956,debit_card,pickup,NaN,NaN
33,34,ORD-20250829-00034,146,2025-08-29,cancelado,1219.270020,14,400,256.049988,1704.619995,cash_on_delivery,express,NaN,NaN
34,35,ORD-20250428-00035,88,2025-04-28,enviado,2946.489990,7,130,618.760010,3489.000000,bank_transfer,pickup,NaN,NaN
35,36,ORD-20240107-00036,182,2024-01-07,cancelado,329.959991,10,110,69.290001,476.250000,paypal,same_day,7.0,NaN
36,37,ORD-20240423-00037,127,2024-04-23,entregado,1629.719971,15,300,342.239990,2027.500000,credit_card,pickup,3.0,NaN
37,38,ORD-20241031-00038,252,2024-10-31,pendiente,3073.810059,1,440,645.500000,4128.569824,bank_transfer,express,NaN,NaN
38,39,ORD-20251112-00039,274,2025-11-12,enviado,2102.129883,20,260,441.450012,2383.149902,debit_card,same_day,6.0,NaN
39,40,ORD-20260118-00040,238,2026-01-18,cancelado,1370.609985,19,220,287.829987,1618.020020,paypal,express,NaN,NaN
45,46,ORD-20231231-00046,253,2023-12-31,entregado,800.130005,20,20,168.029999,828.130005,bank_transfer,express,NaN,NaN
46,47,ORD-20240704-00047,263,2024-07-04,entregado,6023.709961,6,150,1264.979980,7077.270020,debit_card,pickup,NaN,NaN
47,48,ORD-20251002-00048,49,2025-10-02,entregado,6350.680176,4,290,1333.640015,7720.290039,debit_card,standard,NaN,NaN
48,49,ORD-20240326-00049,219,2024-03-26,enviado,1762.239990,6,90,370.070007,2116.580078,cash_on_delivery,pickup,3.0,NaN
49,50,ORD-20240112-00050,178,2024-01-12,procesando,3920.110107,18,120,823.219971,4157.709961,cash_on_delivery,pickup,NaN,NaN
50,51,ORD-20240629-00051,84,2024-06-29,pendiente,3090.899902,16,390,649.090027,3635.449951,credit_card,express,NaN,NaN
51,52,ORD-20250801-00052,48,2025-08-01,entregado,3182.649902,15,470,668.359985,3843.610107,debit_card,express,NaN,NaN
52,53,ORD-20250914-00053,36,2025-09-14,entregado,1054.560059,11,30,221.460007,1190.020020,cash_on_delivery,pickup,NaN,NaN
53,54,ORD-20250525-00054,38,2025-05-25,enviado,565.989990,9,460,118.860001,1093.910034,credit_card,pickup,NaN,NaN
55,56,ORD-20231009-00056,85,2023-10-09,enviado,2841.899902,1,190,596.799988,3600.280029,cash_on_delivery,pickup,NaN,NaN
56,57,ORD-20230105-00057,277,2023-01-05,pendiente,911.520020,1,80,191.419998,1173.819946,debit_card,pickup,2.0,NaN
58,59,ORD-20240318-00059,28,2024-03-18,procesando,3401.620117,2,120,714.340027,4167.930176,cash_on_delivery,pickup,NaN,NaN
59,60,ORD-20260302-00060,326,2026-03-02,cancelado,919.559998,5,50,193.110001,1116.689941,paypal,pickup,NaN,NaN
60,61,ORD-20251126-00061,265,2025-11-26,entregado,3321.989990,18,170,697.619995,3591.649902,credit_card,same_day,NaN,NaN
61,62,ORD-20230208-00062,316,2023-02-08,pendiente,133.080002,9,110,27.950001,259.049988,bank_transfer,pickup,NaN,NaN
63,64,ORD-20231018-00064,6,2023-10-18,procesando,1563.329956,18,40,328.299988,1650.229980,bank_transfer,pickup,3.0,NaN
64,65,ORD-20231007-00065,329,2023-10-07,enviado,2406.929932,4,410,505.459991,3226.110107,paypal,standard,1.0,NaN
65,66,ORD-20240227-00066,277,2024-02-27,enviado,4309.839844,13,40,905.070007,4694.629883,paypal,same_day,NaN,NaN
67,68,ORD-20250917-00068,221,2025-09-17,enviado,1530.780029,15,60,321.459991,1682.619995,bank_transfer,pickup,NaN,NaN
68,69,ORD-20230306-00069,176,2023-03-06,cancelado,2608.260010,8,0,547.729980,2947.330078,paypal,same_day,5.0,NaN
69,70,ORD-20231103-00070,247,2023-11-03,pendiente,212.199997,20,90,44.560001,304.320007,cash_on_delivery,express,NaN,NaN
70,71,ORD-20240626-00071,241,2024-06-26,enviado,953.390015,13,350,200.210007,1379.660034,credit_card,express,NaN,NaN
71,72,ORD-20241022-00072,87,2024-10-22,enviado,2045.489990,5,470,429.549988,2842.770020,paypal,pickup,NaN,NaN
72,73,ORD-20240713-00073,330,2024-07-13,entregado,4186.459961,15,0,879.159973,4437.649902,debit_card,standard,NaN,NaN
73,74,ORD-20240717-00074,279,2024-07-17,enviado,3854.840088,18,290,809.520020,4260.490234,debit_card,express,8.0,NaN
74,75,ORD-20260108-00075,259,2026-01-08,cancelado,3052.139893,2,400,640.950012,4032.050049,cash_on_delivery,express,NaN,NaN
75,76,ORD-20240617-00076,68,2024-06-17,pendiente,3042.080078,3,250,638.840027,3839.659912,credit_card,pickup,NaN,NaN
76,77,ORD-20260220-00077,56,2026-02-20,pendiente,1297.020020,14,180,272.369995,1567.810059,paypal,standard,NaN,NaN
77,78,ORD-20260215-00078,316,2026-02-15,entregado,2372.090088,8,190,498.140015,2870.459961,debit_card,same_day,NaN,NaN
78,79,ORD-20250908-00079,140,2025-09-08,enviado,602.619995,9,190,126.550003,864.929993,debit_card,express,NaN,NaN
80,81,ORD-20230906-00081,287,2023-09-06,enviado,3544.270020,14,0,744.299988,3792.370117,cash_on_delivery,same_day,NaN,NaN
81,82,ORD-20230519-00082,125,2023-05-19,cancelado,2771.659912,18,160,582.049988,3014.810059,paypal,standard,4.0,NaN
84,85,ORD-20250113-00085,72,2025-01-13,procesando,1263.619995,6,420,265.359985,1873.160034,paypal,same_day,NaN,NaN
85,86,ORD-20231016-00086,222,2023-10-16,pendiente,1372.650024,17,220,288.260010,1647.560059,credit_card,express,NaN,NaN
86,87,ORD-20251121-00087,240,2025-11-21,enviado,438.570007,12,160,92.099998,638.039978,credit_card,express,10.0,NaN
87,88,ORD-20260201-00088,178,2026-02-01,pendiente,104.690002,2,100,21.980000,224.580002,debit_card,standard,NaN,NaN
88,89,ORD-20241214-00089,57,2024-12-14,entregado,2534.169922,10,490,532.179993,3302.929932,paypal,standard,NaN,NaN
89,90,ORD-20240421-00090,234,2024-04-21,enviado,1982.369995,9,0,416.299988,2220.260010,bank_transfer,pickup,NaN,NaN
90,91,ORD-20240612-00091,39,2024-06-12,entregado,366.359985,10,190,76.940002,596.659973,credit_card,same_day,NaN,NaN
91,92,ORD-20230321-00092,277,2023-03-21,procesando,2816.310059,17,360,591.429993,3288.969971,bank_transfer,same_day,NaN,NaN
92,93,ORD-20250710-00093,209,2025-07-10,pendiente,3700.560059,9,180,777.119995,4324.629883,paypal,standard,NaN,NaN
93,94,ORD-20250710-00094,130,2025-07-10,procesando,3184.929932,7,250,668.840027,3880.820068,credit_card,standard,NaN,NaN
94,95,ORD-20230421-00095,102,2023-04-21,pendiente,520.400024,7,500,109.279999,1093.250000,debit_card,standard,NaN,NaN
95,96,ORD-20231118-00096,223,2023-11-18,enviado,989.119995,3,370,207.720001,1537.170044,cash_on_delivery,same_day,NaN,NaN
96,97,ORD-20240715-00097,244,2024-07-15,pendiente,5226.959961,13,110,1097.660034,5755.120117,cash_on_delivery,standard,NaN,NaN
97,98,ORD-20230812-00098,54,2023-08-12,entregado,2346.459961,0,420,492.760010,3259.219971,bank_transfer,standard,6.0,NaN
99,100,ORD-20240820-00100,281,2024-08-20,cancelado,4252.250000,8,50,892.969971,4855.040039,credit_card,standard,NaN,NaN
100,101,ORD-20250214-00101,141,2025-02-14,cancelado,3148.550049,19,290,661.200012,3501.530029,paypal,pickup,1.0,NaN
101,102,ORD-20230417-00102,281,2023-04-17,procesando,1718.719971,1,360,360.929993,2422.459961,credit_card,express,NaN,NaN
102,103,ORD-20240223-00103,143,2024-02-23,cancelado,3279.360107,19,480,688.669983,3824.949951,bank_transfer,pickup,NaN,NaN
103,104,ORD-20240107-00104,22,2024-01-07,entregado,3048.689941,19,0,640.219971,3109.659912,paypal,same_day,3.0,NaN
104,105,ORD-20250214-00105,125,2025-02-14,enviado,6054.459961,3,300,1271.439941,7444.270020,credit_card,same_day,NaN,NaN
105,106,ORD-20250206-00106,328,2025-02-06,entregado,5136.080078,10,400,1078.579956,6101.049805,debit_card,express,NaN,NaN
107,108,ORD-20240208-00108,87,2024-02-08,procesando,194.940002,10,430,40.939999,646.390015,credit_card,standard,NaN,NaN
108,109,ORD-20240119-00109,218,2024-01-19,enviado,2512.669922,19,30,527.659973,2592.919922,credit_card,express,10.0,NaN
110,111,ORD-20250805-00111,15,2025-08-05,enviado,1334.790039,18,270,280.309998,1644.839966,cash_on_delivery,express,1.0,NaN
112,113,ORD-20240103-00113,278,2024-01-03,procesando,3248.570068,19,20,682.200012,3333.540039,bank_transfer,pickup,NaN,NaN
114,115,ORD-20240728-00115,239,2024-07-28,entregado,2208.830078,14,290,463.850006,2653.439941,credit_card,standard,NaN,NaN
115,116,ORD-20260122-00116,246,2026-01-22,entregado,2139.560059,9,410,449.309998,2806.310059,debit_card,pickup,NaN,NaN
116,117,ORD-20230713-00117,186,2023-07-13,entregado,1329.839966,9,30,279.269989,1519.420044,credit_card,same_day,NaN,NaN
117,118,ORD-20250625-00118,113,2025-06-25,pendiente,1158.020020,12,170,243.179993,1432.239990,debit_card,pickup,NaN,NaN
118,119,ORD-20241227-00119,110,2024-12-27,pendiente,637.590027,8,80,133.889999,800.469971,credit_card,express,4.0,NaN
119,120,ORD-20250502-00120,217,2025-05-02,pendiente,710.940002,5,70,149.300003,894.690002,paypal,standard,NaN,NaN
121,122,ORD-20240116-00122,123,2024-01-16,entregado,1713.689941,12,20,359.869995,1887.920044,bank_transfer,pickup,NaN,NaN
123,124,ORD-20250117-00124,97,2025-01-17,entregado,387.660004,7,500,81.410004,941.929993,debit_card,standard,NaN,NaN
124,125,ORD-20250811-00125,286,2025-08-11,cancelado,897.000000,13,380,188.369995,1348.760010,cash_on_delivery,standard,NaN,NaN
125,126,ORD-20231112-00126,159,2023-11-12,enviado,733.710022,10,150,154.080002,964.419983,debit_card,express,5.0,NaN
126,127,ORD-20240816-00127,302,2024-08-16,entregado,4790.419922,7,150,1005.989990,5611.080078,cash_on_delivery,standard,NaN,NaN
127,128,ORD-20231202-00128,162,2023-12-02,enviado,3791.389893,3,280,796.190002,4753.839844,credit_card,pickup,NaN,NaN
128,129,ORD-20241128-00129,190,2024-11-28,enviado,1599.079956,18,230,335.809998,1877.060059,cash_on_delivery,express,NaN,NaN
129,130,ORD-20250830-00130,96,2025-08-30,pendiente,2909.110107,10,40,610.909973,3269.110107,cash_on_delivery,same_day,9.0,NaN
130,131,ORD-20241026-00131,208,2024-10-26,pendiente,1011.359985,13,360,212.389999,1452.270020,debit_card,same_day,NaN,NaN
131,132,ORD-20231213-00132,147,2023-12-13,enviado,2963.449951,7,120,622.320007,3498.330078,debit_card,standard,6.0,NaN
133,134,ORD-20240512-00134,233,2024-05-12,pendiente,2161.959961,15,240,454.010010,2531.679932,bank_transfer,express,6.0,NaN
136,137,ORD-20231029-00137,102,2023-10-29,entregado,1277.959961,1,150,268.369995,1683.550049,credit_card,same_day,9.0,NaN
137,138,ORD-20230805-00138,252,2023-08-05,cancelado,969.150024,19,470,203.520004,1458.530029,debit_card,pickup,NaN,NaN
138,139,ORD-20250615-00139,117,2025-06-15,pendiente,334.019989,15,270,70.139999,624.059998,paypal,express,8.0,NaN
139,140,ORD-20230904-00140,276,2023-09-04,enviado,1489.089966,18,340,312.709991,1873.760010,cash_on_delivery,pickup,NaN,NaN
140,141,ORD-20231028-00141,234,2023-10-28,procesando,2410.739990,17,420,506.260010,2927.169922,cash_on_delivery,standard,NaN,NaN
141,142,ORD-20231117-00142,238,2023-11-17,cancelado,779.450012,7,420,163.679993,1308.569946,cash_on_delivery,same_day,NaN,NaN
142,143,ORD-20230926-00143,323,2023-09-26,cancelado,114.930000,8,120,24.139999,249.880005,debit_card,pickup,4.0,NaN
143,144,ORD-20230503-00144,334,2023-05-03,cancelado,975.880005,2,450,204.929993,1611.290039,bank_transfer,express,NaN,NaN
144,145,ORD-20240605-00145,261,2024-06-05,entregado,4317.379883,4,30,906.650024,5081.330078,bank_transfer,express,NaN,NaN
145,146,ORD-20240905-00146,135,2024-09-05,cancelado,492.179993,4,270,103.360001,845.849976,credit_card,pickup,8.0,NaN
146,147,ORD-20260308-00147,37,2026-03-08,pendiente,2493.429932,18,150,523.619995,2718.229980,cash_on_delivery,same_day,NaN,NaN
147,148,ORD-20250126-00148,140,2025-01-26,entregado,2437.100098,3,450,511.790009,3325.780029,paypal,pickup,NaN,NaN
148,149,ORD-20250130-00149,264,2025-01-30,enviado,2465.949951,16,450,517.849976,3039.250000,credit_card,express,NaN,NaN
150,151,ORD-20250730-00151,91,2025-07-30,procesando,388.040009,2,460,81.489998,921.770020,credit_card,standard,NaN,NaN
152,153,ORD-20250517-00153,312,2025-05-17,enviado,2218.060059,4,300,465.790009,2895.129883,credit_card,standard,NaN,NaN
157,158,ORD-20240314-00158,233,2024-03-14,cancelado,4190.370117,1,230,879.979980,5258.450195,bank_transfer,pickup,NaN,NaN
158,159,ORD-20250517-00159,174,2025-05-17,cancelado,775.320007,20,370,162.820007,1153.079956,bank_transfer,standard,NaN,NaN
159,160,ORD-20230316-00160,314,2023-03-16,pendiente,326.559998,12,320,68.580002,675.950012,bank_transfer,same_day,NaN,NaN
160,161,ORD-20241201-00161,95,2024-12-01,enviado,1335.859985,10,390,280.529999,1872.800049,paypal,same_day,4.0,NaN
161,162,ORD-20250224-00162,31,2025-02-24,cancelado,3675.770020,16,150,771.909973,4009.560059,debit_card,pickup,NaN,NaN
162,163,ORD-20230527-00163,248,2023-05-27,pendiente,4135.689941,1,400,868.489990,5362.819824,cash_on_delivery,standard,NaN,NaN
163,164,ORD-20251229-00164,167,2025-12-29,cancelado,4168.379883,8,440,875.359985,5150.270020,credit_card,same_day,NaN,NaN
164,165,ORD-20250306-00165,33,2025-03-06,entregado,2890.489990,10,60,607.000000,3268.439941,paypal,same_day,NaN,NaN
165,166,ORD-20230424-00166,233,2023-04-24,pendiente,4629.740234,18,270,972.250000,5038.640137,paypal,standard,NaN,NaN
166,167,ORD-20230921-00167,279,2023-09-21,pendiente,3179.330078,19,350,667.659973,3592.919922,credit_card,same_day,NaN,NaN
167,168,ORD-20240304-00168,325,2024-03-04,entregado,1239.060059,3,50,260.200012,1512.089966,bank_transfer,standard,NaN,NaN
168,169,ORD-20241107-00169,283,2024-11-07,cancelado,3395.870117,1,420,713.130005,4495.040039,paypal,same_day,1.0,NaN
169,170,ORD-20251128-00170,319,2025-11-28,enviado,1277.959961,19,150,268.369995,1453.520020,cash_on_delivery,pickup,8.0,NaN
170,171,ORD-20260221-00171,163,2026-02-21,procesando,268.000000,12,140,56.279999,432.119995,credit_card,pickup,NaN,NaN
171,172,ORD-20250812-00172,36,2025-08-12,enviado,4544.890137,13,180,954.429993,5088.479980,bank_transfer,same_day,NaN,NaN
172,173,ORD-20240914-00173,241,2024-09-14,pendiente,1767.160034,20,110,371.100006,1894.829956,debit_card,express,NaN,NaN
173,174,ORD-20260204-00174,218,2026-02-04,pendiente,2688.870117,15,130,564.659973,2980.199951,paypal,standard,3.0,NaN
174,175,ORD-20240127-00175,11,2024-01-27,cancelado,1206.800049,19,200,253.429993,1430.939941,paypal,standard,5.0,NaN
175,176,ORD-20251117-00176,194,2025-11-17,cancelado,2919.909912,2,490,613.179993,3964.689941,paypal,express,NaN,NaN
176,177,ORD-20240717-00177,52,2024-07-17,pendiente,1380.910034,0,350,289.989990,2020.900024,debit_card,express,3.0,NaN
177,178,ORD-20241226-00178,168,2024-12-26,entregado,5770.640137,0,470,1211.829956,7452.470215,credit_card,express,NaN,NaN
178,179,ORD-20250330-00179,73,2025-03-30,enviado,2812.300049,9,190,590.580017,3339.770020,credit_card,pickup,NaN,NaN
179,180,ORD-20240915-00180,65,2024-09-15,pendiente,4048.939941,20,180,850.280029,4269.430176,bank_transfer,standard,NaN,NaN
180,181,ORD-20230502-00181,24,2023-05-02,entregado,1635.479980,19,310,343.450012,1978.189941,credit_card,pickup,NaN,NaN
181,182,ORD-20231028-00182,228,2023-10-28,pendiente,764.349976,5,260,160.509995,1146.640015,debit_card,standard,8.0,NaN
182,183,ORD-20230220-00183,215,2023-02-20,procesando,940.280029,18,480,197.460007,1448.489990,debit_card,express,NaN,NaN
183,184,ORD-20250904-00184,231,2025-09-04,procesando,4043.060059,8,500,849.039978,5068.660156,credit_card,same_day,NaN,NaN
185,186,ORD-20230703-00186,126,2023-07-03,entregado,2957.139893,5,330,621.000000,3760.280029,cash_on_delivery,same_day,NaN,NaN
186,187,ORD-20240202-00187,33,2024-02-02,cancelado,1830.219971,15,410,384.350006,2350.040039,bank_transfer,express,2.0,NaN
187,188,ORD-20240529-00188,155,2024-05-29,enviado,3529.580078,12,140,741.210022,3987.239990,bank_transfer,same_day,NaN,NaN
188,189,ORD-20241202-00189,186,2024-12-02,entregado,1508.900024,19,490,316.869995,2029.079956,paypal,pickup,NaN,NaN
190,191,ORD-20240126-00191,220,2024-01-26,entregado,384.619995,4,40,80.769997,490.010010,bank_transfer,pickup,NaN,NaN
191,192,ORD-20240206-00192,20,2024-02-06,cancelado,1955.119995,12,270,410.579987,2401.090088,paypal,standard,NaN,NaN
192,193,ORD-20231230-00193,223,2023-12-30,cancelado,4623.600098,20,50,970.960022,4719.839844,paypal,pickup,NaN,NaN
193,194,ORD-20250425-00194,70,2025-04-25,procesando,3750.340088,2,260,787.570007,4722.899902,paypal,standard,NaN,NaN
194,195,ORD-20240817-00195,328,2024-08-17,entregado,1905.430054,6,350,400.140015,2541.239990,bank_transfer,standard,NaN,NaN
195,196,ORD-20260214-00196,156,2026-02-14,entregado,3170.550049,5,350,665.820007,4027.840088,cash_on_delivery,express,NaN,NaN
196,197,ORD-20231103-00197,89,2023-11-03,entregado,2013.619995,19,320,422.859985,2373.889893,cash_on_delivery,standard,NaN,NaN
197,198,ORD-20230525-00198,56,2023-05-25,cancelado,2348.540039,14,90,493.190002,2602.929932,bank_transfer,same_day,6.0,NaN
199,200,ORD-20230224-00200,108,2023-02-24,pendiente,2669.719971,3,470,560.640015,3620.270020,cash_on_delivery,standard,NaN,NaN
200,201,ORD-20240627-00201,312,2024-06-27,procesando,3270.030029,9,330,686.710022,3992.439941,debit_card,express,NaN,NaN
201,202,ORD-20250415-00202,76,2025-04-15,procesando,2399.860107,16,10,503.970001,2529.850098,cash_on_delivery,pickup,NaN,NaN
202,203,ORD-20240726-00203,324,2024-07-26,cancelado,232.990005,10,110,48.930000,368.619995,debit_card,standard,NaN,NaN
203,204,ORD-20230920-00204,322,2023-09-20,cancelado,3989.649902,16,350,837.830017,4539.140137,credit_card,express,NaN,NaN

Ahora procedemos a verificar si hay valores repetidos en los datasets

In [325]:
# Diccionario para guardar solo los que tienen duplicados
dfs_con_duplicados = {}

for name, df in datasets.items():
    cantidad_duplicados = df.duplicated().sum()
    
    if cantidad_duplicados > 0:
        dfs_con_duplicados[name] = cantidad_duplicados
        print(f"⚠️  Archivo '{name}' tiene {cantidad_duplicados} filas duplicadas.")
    else:
        print(f"✅ Archivo '{name}' NO tiene duplicados.")

print(f"\nTotal de archivos a revisar: {len(dfs_con_duplicados)}")

✅ Archivo 'ecommerce_brands' NO tiene duplicados.
✅ Archivo 'ecommerce_categories' NO tiene duplicados.
✅ Archivo 'ecommerce_customers' NO tiene duplicados.
✅ Archivo 'ecommerce_inventory' NO tiene duplicados.
✅ Archivo 'ecommerce_orders' NO tiene duplicados.
✅ Archivo 'ecommerce_order_items' NO tiene duplicados.
✅ Archivo 'ecommerce_products' NO tiene duplicados.
✅ Archivo 'ecommerce_promotions' NO tiene duplicados.
✅ Archivo 'ecommerce_reviews' NO tiene duplicados.
✅ Archivo 'ecommerce_suppliers' NO tiene duplicados.
✅ Archivo 'ecommerce_warehouses' NO tiene duplicados.

Total de archivos a revisar: 0

Buscamos si hay algún tipo de dato a corregir

In [326]:
for name, df in datasets.items():
    print(f"Dataset: {name}")

Dataset: ecommerce_brands
Dataset: ecommerce_categories
Dataset: ecommerce_customers
Dataset: ecommerce_inventory
Dataset: ecommerce_orders
Dataset: ecommerce_order_items
Dataset: ecommerce_products
Dataset: ecommerce_promotions
Dataset: ecommerce_reviews
Dataset: ecommerce_suppliers
Dataset: ecommerce_warehouses

In [327]:
categories = datasets["ecommerce_categories"]
categories.info()
print(categories.dtypes)

categories.head(10)

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   category_id         10 non-null     int8
 1   category_name       10 non-null     str
 2   description         10 non-null     str
 3   parent_category_id  3 non-null      float32
 4   is_active           10 non-null     bool
 5   display_order       10 non-null     int8
dtypes: bool(1), float32(1), int8(2), str(2)
memory usage: 362.0 bytes
category_id              int8
category_name             str
description               str
parent_category_id    float32
is_active                bool
display_order            int8
dtype: object

,category_id,category_name,description,parent_category_id,is_active,display_order
0,1,Electrónica,Productos de electrónica,NaN,True,1
1,2,Ropa,Productos de ropa,NaN,True,2
2,3,Hogar,Productos de hogar,NaN,True,3
3,4,Deportes,Productos de deportes,NaN,True,4
4,5,Libros,Productos de libros,4.0,True,5
5,6,Juguetes,Productos de juguetes,5.0,True,6
6,7,Belleza,Productos de belleza,NaN,True,7
7,8,Alimentos,Productos de alimentos,NaN,False,8
8,9,Jardín,Productos de jardín,NaN,True,9
9,10,Automotriz,Productos de automotriz,4.0,True,10

Corregimos el tipo de dato parent_category_id de float a int32

In [328]:
categories["parent_category_id"] = categories["parent_category_id"].astype("Int32")
print(categories.dtypes)
categories.head(10)

category_id            int8
category_name           str
description             str
parent_category_id    Int32
is_active              bool
display_order          int8
dtype: object

,category_id,category_name,description,parent_category_id,is_active,display_order
0,1,Electrónica,Productos de electrónica,<NA>,True,1
1,2,Ropa,Productos de ropa,<NA>,True,2
2,3,Hogar,Productos de hogar,<NA>,True,3
3,4,Deportes,Productos de deportes,<NA>,True,4
4,5,Libros,Productos de libros,4,True,5
5,6,Juguetes,Productos de juguetes,5,True,6
6,7,Belleza,Productos de belleza,<NA>,True,7
7,8,Alimentos,Productos de alimentos,<NA>,False,8
8,9,Jardín,Productos de jardín,<NA>,True,9
9,10,Automotriz,Productos de automotriz,4,True,10

In [329]:
customers = datasets["ecommerce_customers"]
customers.info()
print(customers.dtypes)
customers.head(10)

<class 'pandas.DataFrame'>
RangeIndex: 334 entries, 0 to 333
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        334 non-null    int16
 1   first_name         334 non-null    category
 2   last_name          334 non-null    category
 3   email              334 non-null    str
 4   phone              334 non-null    str
 5   birth_date         334 non-null    str
 6   city               334 non-null    category
 7   country            334 non-null    category
 8   postal_code        334 non-null    int32
 9   segment            334 non-null    category
 10  registration_date  334 non-null    str
 11  last_login         334 non-null    str
 12  is_verified        334 non-null    bool
 13  accepts_marketing  334 non-null    int8
dtypes: bool(1), category(5), int16(1), int32(1), int8(1), str(5)
memory usage: 18.1 KB
customer_id             int16
first_name           category
last_name            category
email                     str
phone                     str
birth_date                str
city                 category
country              category
postal_code             int32
segment              category
registration_date         str
last_login                str
is_verified              bool
accepts_marketing        int8
dtype: object

,customer_id,first_name,last_name,email,phone,birth_date,city,country,postal_code,segment,registration_date,last_login,is_verified,accepts_marketing
0,1,Pedro,Fernández,pedro.fernández1@email.com,+1 855-934-2501,2005-01-26,Córdoba,Argentina,12469,Silver,2023-01-10,2024-07-10,True,0
1,2,Diego,López,diego.lópez2@email.com,+1 592-110-4122,1968-03-30,Tucumán,Argentina,28567,Platinum,2024-02-15,2024-07-02,True,1
2,3,Ana,Fernández,ana.fernández3@email.com,+1 645-895-5732,1986-11-19,Buenos Aires,Chile,37948,Bronze,2021-01-31,2022-08-04,True,1
3,4,Laura,Fernández,laura.fernández4@email.com,+1 724-383-4643,1998-01-20,Buenos Aires,México,71273,Silver,2021-10-22,2022-04-11,False,0
4,5,Lucía,Ramírez,lucía.ramírez5@email.com,+1 237-627-5106,1981-07-13,Mar del Plata,Argentina,37986,Silver,2022-08-08,2024-10-18,False,1
5,6,Lucas,López,lucas.lópez6@email.com,+1 521-510-6518,1965-02-02,Mendoza,Argentina,28800,Bronze,2020-06-09,2020-09-18,True,0
6,7,Juan,Sánchez,juan.sánchez7@email.com,+1 357-696-3958,1987-03-15,Buenos Aires,Argentina,70612,Platinum,2021-02-15,2023-10-20,True,1
7,8,Mateo,González,mateo.gonzález8@email.com,+1 401-783-4847,1964-07-05,Mendoza,Colombia,69822,Bronze,2020-10-30,2023-03-14,False,1
8,9,Lucas,López,lucas.lópez9@email.com,+1 421-762-8839,1976-06-28,Rosario,Colombia,52532,Gold,2023-09-04,2024-09-01,False,1
9,10,Camila,González,camila.gonzález10@email.com,+1 369-902-3292,1975-01-10,Rosario,Colombia,96513,Bronze,2022-01-13,2023-06-27,True,1

Modificamos algunos campos del dataset customers
first_name y last_name a str
birth_date, registration_date y last_login a datetime
accepts_marketing de int8 a booleano

In [330]:
customers = transform_customers(customers)
print(customers.dtypes)
customers.head(10)

customer_id                   int16
first_name                   string
last_name                    string
email                           str
phone                           str
birth_date           datetime64[us]
city                       category
country                    category
postal_code                   int32
segment                    category
registration_date    datetime64[us]
last_login           datetime64[us]
is_verified                    bool
accepts_marketing              bool
dtype: object

,customer_id,first_name,last_name,email,phone,birth_date,city,country,postal_code,segment,registration_date,last_login,is_verified,accepts_marketing
0,1,Pedro,Fernández,pedro.fernández1@email.com,+1 855-934-2501,2005-01-26,Córdoba,Argentina,12469,Silver,2023-01-10,2024-07-10,True,False
1,2,Diego,López,diego.lópez2@email.com,+1 592-110-4122,1968-03-30,Tucumán,Argentina,28567,Platinum,2024-02-15,2024-07-02,True,True
2,3,Ana,Fernández,ana.fernández3@email.com,+1 645-895-5732,1986-11-19,Buenos Aires,Chile,37948,Bronze,2021-01-31,2022-08-04,True,True
3,4,Laura,Fernández,laura.fernández4@email.com,+1 724-383-4643,1998-01-20,Buenos Aires,México,71273,Silver,2021-10-22,2022-04-11,False,False
4,5,Lucía,Ramírez,lucía.ramírez5@email.com,+1 237-627-5106,1981-07-13,Mar del Plata,Argentina,37986,Silver,2022-08-08,2024-10-18,False,True
5,6,Lucas,López,lucas.lópez6@email.com,+1 521-510-6518,1965-02-02,Mendoza,Argentina,28800,Bronze,2020-06-09,2020-09-18,True,False
6,7,Juan,Sánchez,juan.sánchez7@email.com,+1 357-696-3958,1987-03-15,Buenos Aires,Argentina,70612,Platinum,2021-02-15,2023-10-20,True,True
7,8,Mateo,González,mateo.gonzález8@email.com,+1 401-783-4847,1964-07-05,Mendoza,Colombia,69822,Bronze,2020-10-30,2023-03-14,False,True
8,9,Lucas,López,lucas.lópez9@email.com,+1 421-762-8839,1976-06-28,Rosario,Colombia,52532,Gold,2023-09-04,2024-09-01,False,True
9,10,Camila,González,camila.gonzález10@email.com,+1 369-902-3292,1975-01-10,Rosario,Colombia,96513,Bronze,2022-01-13,2023-06-27,True,True

In [331]:
inventory = datasets["ecommerce_inventory"]

inventory = transform_inventory(inventory)
print(inventory.dtypes)

inventory_id                  int16
product_id                     int8
warehouse_id                   int8
quantity                      int16
min_stock_level                int8
max_stock_level               int16
last_restock_date    datetime64[us]
dtype: object

In [332]:
orders = datasets["ecommerce_orders"]
print(orders.dtypes)
orders.head(5)

order_id               int16
order_number             str
customer_id            int16
order_date               str
status              category
subtotal             float32
discount_percent        int8
shipping_cost          int16
tax_amount           float32
total_amount         float32
payment_method      category
shipping_method     category
promotion_id         float32
notes               category
dtype: object

,order_id,order_number,customer_id,order_date,status,subtotal,discount_percent,shipping_cost,tax_amount,total_amount,payment_method,shipping_method,promotion_id,notes
0,1,ORD-20230131-00001,131,2023-01-31,enviado,2923.739990,6,440,613.989990,3802.310059,paypal,same_day,NaN,Nota del cliente: Envolver para regalo
1,2,ORD-20230315-00002,21,2023-03-15,procesando,1379.520020,6,360,289.700012,1946.449951,paypal,same_day,10.0,NaN
2,3,ORD-20250807-00003,313,2025-08-07,enviado,1652.000000,16,30,346.920013,1764.599976,debit_card,express,NaN,NaN
3,4,ORD-20250811-00004,195,2025-08-11,procesando,1489.880005,2,300,312.869995,2072.949951,paypal,pickup,7.0,NaN
4,5,ORD-20251012-00005,257,2025-10-12,enviado,989.119995,6,470,207.720001,1607.489990,bank_transfer,same_day,NaN,NaN

Modificamos algunos campos del dataset orders
order_date a datetime
promotion_id de float a int
notes de category a string

In [333]:
orders = transform_orders(orders)
print(orders.dtypes)

order_id                     int16
order_number                   str
customer_id                  int16
order_date          datetime64[us]
status                    category
subtotal                   float32
discount_percent              int8
shipping_cost                int16
tax_amount                 float32
total_amount               float32
payment_method            category
shipping_method           category
promotion_id                  Int8
notes                       string
dtype: object

In [334]:
products = datasets["ecommerce_products"]
print(products.dtypes)

products.head(5)

product_id         int8
sku                 str
product_name        str
description         str
category_id        int8
brand_id           int8
supplier_id        int8
price           float32
cost            float32
weight_kg       float32
is_active          bool
created_at          str
updated_at          str
dtype: object

,product_id,sku,product_name,description,category_id,brand_id,supplier_id,price,cost,weight_kg,is_active,created_at,updated_at
0,1,SKU-000001,Elite Kit 1,Descripción detallada del producto 1,4,2,4,260.570007,148.520004,32.900002,True,2023-07-16,2026-02-21
1,2,SKU-000002,Mini Producto 2,Descripción detallada del producto 2,8,3,6,135.970001,81.580002,16.500000,False,2022-07-31,2024-09-26
2,3,SKU-000003,Elite Set 3,Descripción detallada del producto 3,5,15,5,301.309998,183.800003,34.400002,True,2022-03-10,2024-11-01
3,4,SKU-000004,Mega Equipo 4,Descripción detallada del producto 4,9,7,8,32.340000,14.880000,37.900002,True,2023-07-24,2025-06-14
4,5,SKU-000005,Max Equipo 5,Descripción detallada del producto 5,8,10,3,478.839996,258.570007,14.400000,True,2023-04-03,2024-09-20

Modificamos los campos created_at y updated_at de str a datetime en ecommerce_products

In [335]:
products = transform_products(products)
print(products.dtypes)

product_id                int8
sku                        str
product_name               str
description                str
category_id               int8
brand_id                  int8
supplier_id               int8
price                  float32
cost                   float32
weight_kg              float32
is_active                 bool
created_at      datetime64[us]
updated_at      datetime64[us]
dtype: object

In [336]:
promotions = datasets["ecommerce_promotions"]
print(promotions.dtypes)
promotions.head(3)

promotion_id            int8
promotion_code           str
promotion_name           str
promotion_type      category
discount_value          int8
min_order_amount       int16
max_uses               int16
current_uses           int16
start_date               str
end_date                 str
is_active               bool
dtype: object

,promotion_id,promotion_code,promotion_name,promotion_type,discount_value,min_order_amount,max_uses,current_uses,start_date,end_date,is_active
0,1,PROMO0EED47,Promoción 1,percentage,8,170,638,406,2024-04-27,2024-07-11,True
1,2,PROMO80EB43,Promoción 2,fixed_amount,32,840,6085,491,2024-01-27,2024-03-15,True
2,3,PROMO7F4F39,Promoción 3,percentage,30,630,8128,15,2024-01-10,2024-03-18,False

Modificamos los campos fecha de ecommerce_promotions

In [337]:
promotions = transform_promotions(promotions)
print(promotions.dtypes)

promotion_id                  int8
promotion_code                 str
promotion_name                 str
promotion_type            category
discount_value                int8
min_order_amount             int16
max_uses                     int16
current_uses                 int16
start_date          datetime64[us]
end_date            datetime64[us]
is_active                     bool
dtype: object

In [338]:
reviews = datasets["ecommerce_reviews"]
print(reviews.dtypes)
reviews.head(5)

review_id                  int16
product_id                  int8
customer_id                int16
rating                      int8
title                   category
comment                 category
is_verified_purchase        bool
helpful_votes               int8
created_at                   str
dtype: object

,review_id,product_id,customer_id,rating,title,comment,is_verified_purchase,helpful_votes,created_at
0,1,77,229,5,Podría mejorar,Cumple con lo prometido.,False,44,2023-12-16
1,2,28,119,5,Buena calidad,Cumple con lo prometido.,True,45,2024-01-06
2,3,16,75,3,No tan bueno,"Superó mis expectativas, lo recomiendo totalme...",True,47,2024-02-26
3,4,26,244,3,Buena calidad,Cumple con lo prometido.,False,16,2023-10-09
4,5,91,205,1,Buena calidad,Llegó a tiempo y en perfecto estado.,True,46,2023-04-17

In [339]:
reviews = transform_reviews(reviews)
print(reviews.dtypes)

review_id                        int16
product_id                        int8
customer_id                      int16
rating                            int8
title                         category
comment                       category
is_verified_purchase              bool
helpful_votes                     int8
created_at              datetime64[us]
dtype: object

In [340]:
suppliers = datasets["ecommerce_suppliers"]
print(suppliers.dtypes)

suppliers.head(5)

supplier_id         int8
supplier_name        str
contact_name         str
email                str
phone                str
address              str
rating           float32
is_active           bool
dtype: object

,supplier_id,supplier_name,contact_name,email,phone,address,rating,is_active
0,1,Distribuidora Norte,Juan Pérez,contact@distribuidoranorte.com,+1 997-115-5178,2043 Rosario,4.2,False
1,2,Importadora Sur,Ana Martínez,contact@importadorasur.com,+1 989-643-6232,2931 La Plata,4.2,True
2,3,Mayorista Central,María García,contact@mayoristacentral.com,+1 934-650-7368,7595 Córdoba,3.8,True
3,4,Logística Express,Carlos López,contact@logísticaexpress.com,+1 362-407-3027,2420 Mar del Plata,3.5,True
4,5,Proveedores Unidos,Carlos López,contact@proveedoresunidos.com,+1 448-550-2292,1861 Santa Fe,4.1,True

In [341]:
warehouses = datasets["ecommerce_warehouses"]
print(warehouses.dtypes)

warehouses.head(5)

warehouse_id          int8
warehouse_name         str
location               str
capacity_units       int32
current_occupancy     int8
manager_name           str
dtype: object

,warehouse_id,warehouse_name,location,capacity_units,current_occupancy,manager_name
0,1,Depósito 1,Buenos Aires,50548,72,Diego Fernández
1,2,Depósito 2,Córdoba,37177,85,Laura Torres
2,3,Depósito 3,Rosario,52044,48,Sofía Ramírez
3,4,Depósito 4,Mendoza,47436,83,Sofía Ramírez
4,5,Depósito 5,La Plata,11129,55,Diego Fernández

1.Cuales son los 5 clientes que más dinero gastaron ?

In [342]:

top_five_clients = (
    pd.merge(orders, customers, on="customer_id")
    .query("status == 'completed'")
    .groupby(["customer_id", "first_name", "last_name"])
    .agg(
        total_orders=("order_id", "count"), 
        total_spent=("total_amount", "sum"))
        .sort_values(by="total_spent", ascending=False).reset_index().head(5)
)

print(top_five_clients)

Empty DataFrame
Columns: [customer_id, first_name, last_name, total_orders, total_spent]
Index: []

2.Cuál es el producto más vendido (por cantidad)

In [343]:
order_items = datasets["ecommerce_order_items"]

most_selled_product = pd.merge(order_items, products, on="product_id").groupby(["product_id", "product_name"]).agg(total_sold=("quantity", "sum")).sort_values(by="total_sold", ascending=False).reset_index().head(1)
print(most_selled_product)

   product_id    product_name  total_sold
0          44  Mega Equipo 44         126

3.Como evolucionaron las ventas mes a mes

In [344]:
orders.head(1)

,order_id,order_number,customer_id,order_date,status,subtotal,discount_percent,shipping_cost,tax_amount,total_amount,payment_method,shipping_method,promotion_id,notes
0,1,ORD-20230131-00001,131,2023-01-31,enviado,2923.73999,6,440,613.98999,3802.310059,paypal,same_day,<NA>,Nota del cliente: Envolver para regalo

In [345]:
sales_by_month = (
    orders
    .query("status != 'cancelado'")
    .groupby([orders["order_date"].dt.year.rename("año"), orders["order_date"].dt.month.rename("mes")])
    .agg(
        total_ventas=("total_amount", "sum"),
    )
)

sales_by_month["porcentaje_crecimiento"] = sales_by_month["total_ventas"].pct_change().round(2).fillna(0) * 100

print(sales_by_month)

          total_ventas  porcentaje_crecimiento
año  mes
2023 1    37909.710938                     0.0
     2    68137.460938                    80.0
     3    39488.878906                   -42.0
     4    58773.531250                    49.0
     5    57834.179688                    -2.0
     6    46536.031250                   -20.0
     7    48476.519531                     4.0
     8    57348.281250                    18.0
     9    30737.830078                   -46.0
     10   59746.730469                    94.0
     11   84217.406250                    41.0
     12   70024.890625                   -17.0
2024 1    66097.484375                    -6.0
     2    71261.921875                     8.0
     3    67306.843750                    -6.0
     4    63494.257812                    -6.0
     5    58305.039062                    -8.0
     6    64488.109375                    11.0
     7    66225.359375                     3.0
     8    66210.078125                    -0.0
     9    53729.621094                   -19.0
     10   50262.031250                    -6.0
     11   43310.628906                   -14.0
     12   52820.628906                    22.0
2025 1    52721.039062                    -0.0
     2    43468.570312                   -18.0
     3    51349.289062                    18.0
     4    59516.890625                    16.0
     5    46471.000000                   -22.0
     6    49675.750000                     7.0
     7    45185.800781                    -9.0
     8    54174.808594                    20.0
     9    68219.468750                    26.0
     10   57638.578125                   -16.0
     11   50832.570312                   -12.0
     12   45539.609375                   -10.0
2026 1    61013.800781                    34.0
     2    51503.429688                   -16.0
     3    25535.300781                   -50.0

Mostramos el total de ventas mes a mes con su porcentaje de crecimiento

Procedemos a guardar en CSV y Parquet

In [ ]:
for name, df in datasets.items():
    load_datasets